### ISSUE TITLE
Create an Individual

### ISSUE THREAD

**Issue by jangrakul** [craiggreenhalgh/springbootapp#2]
Add an Individual using following fields.
    
    "title": string,
    "name": {
      "firstName": string,
      "lastName": string
    },
    "dob": date,
    "address": {
      "addressLine1": string,
      "addressLine2": string,
      "county": string,
      "country": string,
      "postCode": string
    }

**Comment by craiggreenhalgh** [comment]
Merged into master branch.  Addresses are maintained outside of this endpoint
